name: open-webui
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    ports:
      - "11808:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama.traefik.localhost:11434
      - ENV=dev
      - WEBUI_AUTH=false
    volumes:
      - open-webui-data:/app/backend/data
    networks:
      - traefik
    labels:
      - traefik.http.routers.openwebui.rule=Host(`openwebui.traefik.localhost`) | Host(`openwebui.docker.localhost`)
      - traefik.http.services.openwebui.loadbalancer.server.port=8080
      - traefik.docker.network=traefik
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - traefik
    labels:
      - traefik.http.routers.ollama.rule=Host(`ollama.traefik.localhost`) | Host(`ollama.docker.localhost`)
      - traefik.http.services.ollama.loadbalancer.server.port=11434
      - traefik.docker.network=traefik
volumes:
  open-webui-data:
  ollama:
networks:
  traefik:
    name: traefik
    external: true

# docker run -d -p 3000:8080 --gpus=all -v ollama:/root/.ollama -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:ollama
