http:
  routers:
    traefik:
      rule: "Host(`dashboard.traefik.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "docker.localhost"
            sans:
              - "*.docker.localhost"
          - main: "traefik.localhost"
            sans:
              - "*.traefik.localhost"
          - main: "dev.localhost"
            sans:
              - "*.dev.localhost"
    ollama:
      rule: "Host(`ollama.traefik.localhost`)"
      service: "ollama@file"
      middlewares:
        - "set-ollama-host"
      entryPoints:
        - http
        - https
  services:
    ollama:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:11434"
  middlewares:
    set-ollama-host:
      headers:
        customRequestHeaders:
          Host: "localhost:11434"

tls:
  certificates:
    - certFile: "/etc/certs/cert.pem"
      keyFile: "/etc/certs/key.pem"
