http:
  routers:
    traefik:
      rule: "Host(`dashboard.traefik.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "docker.localhost"
            sans:
              - "*.docker.localhost"
          - main: "traefik.localhost"
            sans:
              - "*.traefik.localhost"

tls:
  certificates:
    - certFile: "/etc/certs/cert.pem"
      keyFile: "/etc/certs/key.pem"