accessLog: {}
log: {}
api:
  insecure: true
  dashboard: true
  debug: true
providers:
  docker:
    network: traefik
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
  file:
    filename: /etc/traefik/config.yml
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
    http:
      tls: {}
  mysql:
    address: ":3306"
  postgres:
    address: ":5432"
